name: Run Tests

on: pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.10.0
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.11.0
      - name: Run BATS Tests
        run: make ci-test
